root: kramer to .
post:
  compiler: kramer
  to: .
  context:
    developing: true
    macros:
    - 'post.macros'
    scripts:
    - '/js/underscore.js'
    - '/js/jquery.js'
    - '/js/raphael.js'
    - '/js/waypoints.js'
    - '@coffee/uriel'
    - '@coffee/post'
mathbox:
  compiler: flow
raphael: coffee to js/diagram
images: copy to images
stylus: css
coffee: js
static: copy to .
diagram: true
