root: kramer to .
post:
  compiler: kramer
  to: .
  context:
    developing: true
    macros:
    - 'post.macros'
    scripts:
    - 'js/jquery.js'
    - '@coffee/post'
mathbox:
  compiler: flow
images: copy to images
stylus: css
coffee: js
static: copy to .
