// Generated by CoffeeScript 1.4.0
(function() {
  var NumberLine, height, numberTick, numberWidth, padding, width,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  width = 500;

  height = 50;

  padding = 50;

  numberTick = 35;

  numberWidth = width - (3 * padding) - numberTick;

  NumberLine = (function(_super) {

    __extends(NumberLine, _super);

    function NumberLine() {
      this.start = __bind(this.start, this);
      return NumberLine.__super__.constructor.apply(this, arguments);
    }

    NumberLine.prototype.start = function() {
      return this.axis(zx - 0.5, zy, this.lineLength, tickCount, {
        capFraction: capFraction
      });
    };

    return NumberLine;

  })(Diagram);

  $(function() {
    return diagram('number-line', NumberLine, width, height);
  });

}).call(this);
