// Generated by CoffeeScript 1.4.0
(function() {
  var Test,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Test = (function(_super) {

    __extends(Test, _super);

    function Test() {
      this.start = __bind(this.start, this);
      return Test.__super__.constructor.apply(this, arguments);
    }

    Test.prototype.start = function() {
      return Axis(this.paper, 250, 250);
    };

    return Test;

  })(Diagram);

  $(function() {
    return diagram('test', Test, 500, 500);
  });

}).call(this);
