// Generated by CoffeeScript 1.4.0
(function() {
  var create;

  $(function() {
    return $('.unroll-pi').each(create);
  });

  create = function() {
    var begin, circle, circumference, fadeIn, fadeOut, height, laid, middle, outline, padding, paper, radine, radius, reset, roll, startx, starty, turns, width;
    width = 500;
    height = 200;
    paper = util.paperFor(this, width, height);
    radius = 45;
    circumference = τ * radius;
    middle = height / 2;
    padding = 15;
    startx = padding + radius;
    starty = middle + radius;
    Raphael.g.axis(startx, starty, 8 * radius, 0, 8, 8, null, 0, 't', null, paper);
    circle = paper.circle();
    outline = paper.path().attr('stroke-width', 2);
    laid = paper.path().attr('stroke-width', 2);
    radine = paper.path().attr('stroke-width', 1);
    turns = paper.text(width - 2 * radius, radius, 0..toFixed(6));
    reset = function() {
      circle.attr({
        cx: startx,
        cy: middle,
        r: radius,
        opacity: 0,
        'stroke-width': 2
      });
      outline.attr({
        circ: [startx, middle, radius, 1, -1 / 4],
        opacity: 0
      });
      laid.attr({
        path: new util.Path(startx, starty).draw(0.01, 0).string
      });
      radine.attr({
        turn: [startx, starty, radius, 0],
        opacity: 1
      });
      return turns.attr({
        turns: 0..toFixed(6),
        opacity: 0
      });
    };
    begin = function() {
      reset();
      return radine.animate({
        turn: [startx, starty, radius, 1 / 4]
      }, 1000, '<>', fadeIn);
    };
    fadeIn = function() {
      var a;
      radine.attr({
        turn: [startx, middle, radius, -1 / 4]
      });
      a = circle.animate({
        opacity: 1
      }, 1000, '<', roll);
      return turns.animateWith(circle, a, {
        opacity: 1
      }, 1000, '<', roll);
    };
    roll = function() {
      var a;
      circle.attr({
        'stroke-width': 0
      });
      outline.attr({
        opacity: 1
      });
      laid.attr({
        opacity: 1
      });
      a = circle.animate({
        cx: startx + (Math.PI * radius)
      }, 2500, '<', function() {
        return setTimeout(fadeOut, 5500);
      });
      radine.animateWith(circle, a, {
        turn: [startx + (Math.PI * radius), middle, radius, -3 / 4]
      }, 2500, '<');
      outline.animateWith(circle, a, {
        circ: [startx + (Math.PI * radius), middle, radius, 1 / 2, -1 / 4]
      }, 2500, '<');
      laid.animateWith(circle, a, {
        path: new util.Path(startx, starty).draw(Math.PI * radius, 0).string
      }, 2500, '<');
      return turns.animateWith(circle, a, {
        turns: 1 / 2
      }, 2500, '<');
    };
    fadeOut = function() {
      var a;
      a = circle.animate({
        opacity: 0
      }, 1000, '<', function() {
        return setTimeout(begin, 1000);
      });
      outline.animateWith(circle, a, {
        opacity: 0
      }, 1000, '<');
      laid.animateWith(circle, a, {
        opacity: 0
      }, 1000, '<');
      radine.animateWith(circle, a, {
        opacity: 0
      }, 1000, '<');
      return turns.animateWith(circle, a, {
        opacity: 0
      }, 1000, '<');
    };
    reset();
    return setTimeout(begin, 3000);
  };

}).call(this);
