// Generated by CoffeeScript 1.6.1
(function() {
  var Test,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Test = (function(_super) {

    __extends(Test, _super);

    function Test() {
      Test.__super__.constructor.apply(this, arguments);
      this.x = this.axis(50, this.height / 2, {
        unit: 40
      });
    }

    return Test;

  })(Uriel.Diagram);

  $(function() {
    return Uriel.diagram('test', Test);
  });

}).call(this);
